### ISSUE TITLE
Borders on windows

### ISSUE THREAD

**Issue by jsaric** [Alexhuszagh/BreezeStyleSheets#10]
Hi, I decided to learn something about PyQt so started developing some simple app. I'm working on Linux, but I would like to run my app on windows also. I really like the dark style whick looks great on Linux.
I noticed that when I run it on Windows 10, borders around almost all widgets are missing. For example that nice blue border around buttons when hovered. Do you know some quick fix for this?

Thank you for your work!

**Comment by Alexhuszagh** [comment]
Can you post pictures? I've used this fairly extensively on Windows ~1-2 years ago (that was actually the initial goal of this stylesheet, for incorporation in a Windows desktop application), however, I have not had access to a native, Windows build machine in ~6 months, so obviously there may be significant differences than my initial intentions.

I can set up a VM with Windows 10 to test this later, but some photos would be useful to diagnose any issues. Can you run `dark.py` and `light.py` to see how the style looks, and just post screenshots of the app?

Thanks.

**Comment by jsaric** [comment]
Hey, I uploaded screenshots from windows and linux on Imgur: https://imgur.com/a/NZ731Do

Currently, I'm also running Windows 10 on virtual machine, but I noticed the same thing on native Windows 10. I think it has something to do with setting the border width with 'ex' unit.

**Comment by Alexhuszagh** [comment]
Perfect thanks, I'll get my virtual machine up and running. Thanks for this, let me know if you find anything that may help this. I'll try changing the padding units and other potential fixes.

**Comment by ghostSAS** [comment]
Hi, thanks for your excellent work Alex! But I had the same issue when I ran on my win10. Though it went well on my mac. 

Looking forward to your fixing

**Comment by allanvobraun** [comment]
Same issue in windows 7, someone managed to fix it?

**Comment by OmarElbekiey** [comment]
Did anyone managed to fix it ?

Wonderful job !!

**Comment by Gyelib** [comment]
I tried to fix it, but it still looks different from the example gif.

Multiply the value by 10 and change the unit from `ex` to `px`,
for example, **0.1ex** -> **1px**, **1ex** -> **10px**, 
and then recompile `breeze_resources.py`.

**Comment by dridk** [comment]
I tried breeze theme on windows, and it looks strange . Seems border are missing too . Here is what it looks like : 
No borders arround button, textedit, tab etc ... 


# Breeze 

![image](https://user-images.githubusercontent.com/1911063/94244966-e89ba080-ff19-11ea-9b35-9f8c82334e0e.png)

# Fusion 
![fusion](https://user-images.githubusercontent.com/1911063/94244783-affbc700-ff19-11ea-972c-6d31ee7e65fe.PNG)

**Comment by adamerose** [comment]
> I tried to fix it, but it still looks different from the example gif.
> 
> Multiply the value by 10 and change the unit from `ex` to `px`,
> for example, **0.1ex** -> **1px**, **1ex** -> **10px**,
> and then recompile `breeze_resources.py`.

This fixed it for me, thank you. 

You can do this with these two regex replacements (in order) in VS Code.
`0\.([0-9])ex` -> `$1px`
`([0-9])ex` -> `$10px`

Before
![image](https://user-images.githubusercontent.com/10884874/97390667-c64bc880-18b3-11eb-8dc2-da80b61edc89.png)

After
![image](https://user-images.githubusercontent.com/10884874/97390656-c2b84180-18b3-11eb-8626-6e1ee24742a5.png)


I guess the `ex` unit isn't supported on some versions of PyQt5 or Windows? I assume there was some reason to choose `ex` over `px` but it seems like my result matches the demo gif so maybe stop using `ex` since it appears to not work for some users?

These are my versions...
OS: Windows 10
Python: 3.8
PyQt: 5.15.1

**Comment by Alexhuszagh** [comment]
I'm working extensively on this, since there's some issues with scaling, and others. For the latest changes, see [windows_dark.qss](https://github.com/Alexhuszagh/BreezeStyleSheets/blob/master/windows_dark.qss), which will eventually replace `dark` and be used as the basis for `light`.

**Comment by Alexhuszagh** [comment]
I've fixed this through extensive changes to the theme. However, unfortunately, I believe using relative units is still the best idea. For better visual UI, I've scaled it relative to `em` rather than `ex` (which is generally preferable), and made sure it looks good on Windows at multiple different font sizes (the app scales to the initial font size provided to the application, prior to the stylesheet being set, but is unaffected by any custom font changes for individual widgets).

As you can see, the tooltips are much better now, as are other borders.

# 8 Point Font (The Default for Me)

![2021-07-16 23_37_56-Borders on windows · Issue #10 · Alexhuszagh_BreezeStyleSheets — Mozilla Firefox](https://user-images.githubusercontent.com/9440903/126025621-0ab16e9c-e763-4a92-8bcc-ea62c2a0a46d.png)

# 12 Point Font (Common Setting)

![2021-07-16 23_38_57-CMD](https://user-images.githubusercontent.com/9440903/126025655-a9fb7e21-c806-4037-bdae-130832bcfc98.png)

# 20 Point Font (Accessibility)

(Please note that the window is larger, which is why the tooltip font looks smaller).

![2021-07-16 23_40_10-Window](https://user-images.githubusercontent.com/9440903/126025677-292e0536-4c1f-449a-b1c3-d575dfe63452.png)

# High DPI Scaling

This uses a scale factor of 2 to test the UI when everything is scaled up.

![2021-07-16 23_42_55-Window](https://user-images.githubusercontent.com/9440903/126025838-e2f16228-8581-4e28-85bb-ac3aba8b1cc3.png)

I believe that handles every expected use-case.
