### ISSUE TITLE
UI File

### ISSUE THREAD

**Issue by onurhanerk** [Alexhuszagh/BreezeStyleSheets#12]
Where can I find the ui file

**Comment by Alexhuszagh** [comment]
Not sure what you mean. There's the compiled resource file, which is generated locally for PyQt5 using `pyrcc5 breeze.qrc -o breeze_resources.py`. There's `example.py`, which is code from an old version of QDarkStylesheet and just Python code for the UI (adapted originally from a `.ui` file). Since it's not the focus of the project, and merely an example of the theme, there's no need to generate Python code from data, we can just have the Python code.
