### ISSUE TITLE
QFileDialog icons are missing

### ISSUE THREAD

**Issue by cdgriffith** [Alexhuszagh/BreezeStyleSheets#22]
When using PyQT5 and either light or dark theme, the icons in a QFileDialog are not there, and just empty buttons. 
![light_issue](https://user-images.githubusercontent.com/3275435/135507157-dc55402e-fb9a-4427-88a1-1026b573f6e3.png)

Without the theme:
![system](https://user-images.githubusercontent.com/3275435/135507199-4c8e0848-3a11-4140-80ff-abe2ce9bec06.png)

Called with the code: 

```
        filename = QtWidgets.QFileDialog.getOpenFileName( self, caption="Open Video")
```

Edit: Super simple program that auto opens the dialog to test with: 

```
import sys

from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

import breeze_resources

class Window(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.resize(400, 200)
        QFileDialog.getOpenFileName()
        raise Exception("end app")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    file = QFile(f":/light/stylesheet.qss")
    file.open(QFile.ReadOnly | QFile.Text)
    stream = QTextStream(file)
    app.setStyleSheet(stream.readAll())
    win = Window()
    win.show()
    sys.exit(app.exec_())


```

**Comment by Alexhuszagh** [comment]
This might be related to this code [here](https://github.com/Alexhuszagh/BreezeStyleSheets/blob/79a9825c268f88aed6e307e76fa97b063c1c4de9/template/stylesheet.qss.in#L1928-L1963).

I'll see if removing those lines fixes the issue, and if so, I'll have to provide my own versions of the QFileDIalog icons. I was trying to avoid this, since normally it defaults to the platform-specific file dialog, which would obviously be ideal. I may be able to disable the styles **specifically** for QFileDialog, and see how that works.

**Comment by cdgriffith** [comment]
Removing that section and testing again with the small script added above doesn't seem to change anything. 

I imagine only a problem on Linux (Ubuntu 20.04.3 tested with PyQT5  5.15.4 and PySide2 5.15.2 ), tested on Windows and all the icons looked right.

**Comment by Alexhuszagh** [comment]
I wonder if this has to do with the desktop environment, since this doesn't reproduce on KDE Plasma using Wayland. I'll try Gnome and XFCE or similar and see if the same issues reproduce, on X11 and Wayland.

**Comment by Alexhuszagh** [comment]
This seems to be related to #28, just one reproduces on PyQt5 and the other on PyQt6.
