### ISSUE TITLE
[QUESTION] Labels with hyperlinks

### ISSUE THREAD

**Issue by felipefarinon** [Alexhuszagh/BreezeStyleSheets#75]
## Question
QLabel can be used to show hyperlinks. Currently, the colors used don't read well in the dark theme. Are there any plans to support them?

![image](https://user-images.githubusercontent.com/17036813/206461749-267a8105-1c09-49e1-a56d-790b2f35d5c9.png)

**Comment by Alexhuszagh** [comment]
Unfortunately, no, because there is no good way for us to style this. The option is to use a custom palette for the application, changing `QPalette::Link` to a new color. There should be an example in the examples directory of how to do this:
- [How do I customise the appearance of links in QLabels using style sheets?](https://stackoverflow.com/questions/5497799/how-do-i-customise-the-appearance-of-links-in-qlabels-using-style-sheets)
- [Customizing QFrame](https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qframe)
